"""Run EgoVerse's official sync_s3.py directly into a Modal Volume.

Before invoking this file, export the current AWS CLI credentials into the
local environment. The EgoVerse R2/registry settings are loaded from the
protected dotenv generated by setup_secret.sh.
"""

from __future__ import annotations

import os
import subprocess

import modal


app = modal.App("egoverse-official-sync")
VOLUME_NAME = "egoverse-zarrs-v2"
volume = modal.Volume.from_name(VOLUME_NAME, create_if_missing=True, version=2)

image = (
    modal.Image.debian_slim(python_version="3.11")
    .apt_install("git")
    .pip_install(
        "torch==2.6.0",
        "boto3",
        "pandas",
        "sqlalchemy",
        "psycopg[binary]",
        "zarr==3.1.5",
        "simplejpeg",
        "tqdm",
        "s5cmd",
    )
    .pip_install(
        "requests",
        "scaleapi",
        "projectaria-tools==2.0.0",
        "scipy",
        "matplotlib",
        "opencv-python-headless",
        "cloudpathlib[s3]",
    )
    .run_commands(
        "git clone https://github.com/GaTech-RL2/EgoVerse.git /opt/EgoVerse",
        "pip install --no-deps -e /opt/EgoVerse",
    )
)

aws_keys = ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"]
if os.environ.get("AWS_SESSION_TOKEN"):
    aws_keys.append("AWS_SESSION_TOKEN")
aws_secret = modal.Secret.from_local_environ(aws_keys)
egoverse_secret = modal.Secret.from_dotenv(
    path="/private/tmp",
    filename="egoverse_env",
)


@app.function(
    image=image,
    secrets=[aws_secret, egoverse_secret],
    volumes={"/egoverse": volume},
    timeout=60 * 60 * 12,
    cpu=4,
    memory=8192,
)
def sync(
    filter_name: str = "aria-fold-clothes",
    workers: int = 32,
    skip_images: bool = True,
):
    # The upstream preset predates the 2026 human-embodiment collapse. Preserve
    # the named filter's intent by identifying Aria through the current rig field.
    sync_script = "/opt/EgoVerse/egomimic/scripts/data_download/sync_s3.py"
    script_text = open(sync_script).read()
    script_text = script_text.replace(
        "row.get('embodiment') == 'aria'",
        "row.get('rig_name') == 'aria_gen1'",
    )
    # Same staleness in the mecka preset: vendor identity moved from `embodiment`
    # to `lab` in the 2026 collapse, so `embodiment == 'mecka'` now matches nothing.
    # Widen the task match too — mecka splits folding across `fold_clothes` (1,607)
    # and `folding_clothes` (462) plus compounds, and the segment-labelled episodes
    # are spread across all of them.
    script_text = script_text.replace(
        "\"lambda row: row.get('embodiment') == 'mecka'\",\n"
        "            \"lambda row: row.get('task') == 'fold_clothes'\",",
        "\"lambda row: row.get('lab') == 'mecka'\",\n"
        "            \"lambda row: 'fold' in (row.get('task') or '').lower()\",",
    )
    with open(sync_script, "w") as script_file:
        script_file.write(script_text)

    # A prior interrupted concurrent sync can leave partial episode directories.
    # The upstream resolver treats directory existence as completion, so force
    # s5cmd to revisit every prefix; s5cmd itself skips objects that already match.
    resolver_script = (
        "/opt/EgoVerse/egomimic/rldb/zarr/zarr_dataset_multi.py"
    )
    resolver_text = open(resolver_script).read()
    resolver_text = resolver_text.replace(
        "def _episode_already_present(cls, local_dir: Path, episode_hash: str) -> bool:\n",
        "def _episode_already_present(cls, local_dir: Path, episode_hash: str) -> bool:\n"
        "        return False  # integrity-safe resume on Modal\n",
    )
    # Video is ~97% of an episode's bytes (an Aria episode is ~187 MB, of which
    # ~182 MB is the images.front_1 chunk) and carries none of the hand-motion
    # signal. Excluding it takes the aria-fold-clothes pull from ~130 GB to
    # ~3.3 GB. Drop skip_images=False to fetch the video too.
    if skip_images:
        resolver_text = resolver_text.replace(
            "lines.append(f'sync \"{src_prefix}\" \"{str(dst)}/\"')",
            "lines.append(f'sync --exclude \"*images*\" "
            '"{src_prefix}" "{str(dst)}/"\')',
        )

    with open(resolver_script, "w") as resolver_file:
        resolver_file.write(resolver_text)

    command = [
        "python",
        sync_script,
        "--local-dir",
        "/egoverse/episodes",
        "--filters",
        filter_name,
        "--workers",
        str(workers),
    ]
    log_path = "/tmp/egoverse-sync.log"
    with open(log_path, "w") as log_file:
        result = subprocess.run(
            command,
            cwd="/opt/EgoVerse",
            stdout=log_file,
            stderr=subprocess.STDOUT,
        )
    if result.returncode:
        with open(log_path) as log_file:
            tail = log_file.readlines()[-80:]
        raise RuntimeError("Official sync failed:\n" + "".join(tail))
    volume.commit()
    return {"volume": VOLUME_NAME, "path": "/episodes", "filter": filter_name}


@app.function(image=image, secrets=[aws_secret, egoverse_secret])
def registry_summary():
    """Return aggregate, non-sensitive Aria values needed to repair the preset."""
    import json

    from egomimic.utils.aws.aws_sql import create_default_engine, episode_table_to_df

    frame = episode_table_to_df(create_default_engine())
    aria = frame[frame["rig_name"].fillna("").eq("aria_gen1")]
    folding = aria[aria["task"].fillna("").str.contains("fold", case=False)]
    summary = {
        "aria_gen1_total": int(len(aria)),
        "embodiments": {
            str(key): int(value)
            for key, value in aria["embodiment"].value_counts().items()
        },
        "fold_tasks": {
            str(key): int(value)
            for key, value in folding["task"].value_counts().items()
        },
        "fold_ready_for_download": int(
            folding["zarr_processed_path"].fillna("").str.strip().ne("").sum()
        ),
    }
    print(json.dumps(summary, indent=2, sort_keys=True))
    return summary


@app.local_entrypoint()
def main(
    filter_name: str = "aria-fold-clothes",
    workers: int = 32,
    skip_images: bool = True,
):
    print(sync.remote(filter_name, workers, skip_images))
